services:
  # Đặt tên service là nginx
  nginx:
    # Đặt tên container là my-nginx
    container_name: my-nginx
    depends_on:
      #  service nginx sẽ phụ thuộc vào container backend.
      #  service nginx sẽ không bao giờ bắt đầu cho đến khi container backend đã bắt đầu và sẵn sàng
      - backend
    restart: always
    build:
      # Nó sẽ đứng ngay root của toàn bộ dự án (Cùng cấp với folder nginx, stackBE, stackeFE) (Khi ta build chung cục frontend ngay trong con nginx)
      context: .
      # Tìm file Dockerfile trong folder nginx để thực hiện quá trình build cục service này
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8001:80
    volumes:
      # Ghi đè file nginx.conf trong folder nginx/config của dự án lên file nginx.conf của folder etc/nginx trong docker
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      # Nó sẽ lấy tất cả nội dung trong thư mục build của cục stackFE và ghi đè lại thư mục html của thằng nginx trong usr/share/nginx/html/
      # - ../stackFE/build/:/usr/share/nginx/html/ 
      # (Chỉ chạy dòng này khi ta build con frontend độc lập, còn nếu build con frontend trong con nginx thì không cần dòng này)

  # Đặt tên service là mysqldb
  
  mysqldb:
    # Docker pull image mysql:5.7 
    image: mysql:5.7
    restart: unless-stopped
    # Đặt tên container là my-db
    container_name: my-db
    # Thực thi các câu lệnh trong tệp init.sql khi start container
    command: --init-file /data/application/init.sql
    volumes:
      # Ghi đè file initDB.sql lên file initDB.sql của folder /data/application
      - ./initDB.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABSE=stack_overflow
    # Con service backend khai báo bên dưới sẽ kết nối vào con service mysqldb này thông qua cổng 3306 
    # 3306 chính là cổng giao tiếp giữa 2 con service mysqldb và backend để chúng có thể nói chuyện với nhau
    # Các service khác khi muốn giao tiếp với con service mysqldb thì chỉ cần khai báo trong file env cổng 3306 này là được
    expose:
      - "3306"

  # Đặt tên service là backend
  backend:
    depends_on:
      #  service backend sẽ phụ thuộc vào container mysqldb.
      #  service backend sẽ không bao giờ bắt đầu cho đến khi container mysqldb đã bắt đầu và sẵn sàng
      - mysqldb
    restart: unless-stopped
    # Đặt tên container là my-backend
    container_name: my-backend
    build:
      # Nó sẽ tìm file Dockerfile trong folder stackBE để build cục service này
      context: ./stackBE
    environment: 
      # Tham số môi trường của thằng docker nó sẽ ghi đè tham số môi trường của ứng dụng của chúng ta
      # Ghi đề lại biến HOST trong file .env của cục stackBE. Lúc này biến HOST trong file .env của cục stackBE sẽ mang giá trị là mysqldb
      - HOST=mysqldb
    links: 
      # container backend sẽ được liên kết với container mysqld. container backend có thể truy cập các dịch vụ được cung cấp bởi container
      # mysqld 
      - mysqldb
    expose: 
      # Lúc này con nginx muốn giao tiếp với con backend thì trong file nginx.conf phải gọi tới port này
      - "8000"

