services:
  nginx:
    container_name: my-project-nginx-fullstack
    build:
      context: .
    ports:
      - 8001:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ../stackFE/build/:/usr/share/nginx/html/

# - ../stackFE/build/:/usr/share/nginx/html/
# Nó sẽ lấy tất cả nội dung trong thư mục build của dự án stackFE và ghi đè lại thư mục html của thằng nginx trong usr/share/nginx/html/

# ./config/nginx.conf:/etc/nginx/nginx.conf
# Ghi đè file nginx.conf trong folder config lên file nginx.conf của folder etc/nginx
